### ISSUE TITLE
readFloat and readInt should return maybes

### ISSUE THREAD

**Issue by davidchambers** [purescript-deprecated/purescript-globals#5] opened 2015-01-30 21:07 UTC
Should these functions return values of type `Maybe Number` rather than `Number`? NaN checks, like null checks, are easy to forget.

**Comment by garyb** [comment] 2015-01-30 21:20
I'm not sure, possibly. `NaN` is a valid number in PureScript (unfortunately) as there are many different ways it can creep in.

**Comment by paf31** [comment] 2015-01-31 07:13
Maybe we could add these as alternatives. The issue is that then Globals would depend on Maybe, which I think is a little bit of a shame.

**Comment by garyb** [comment] 2015-01-31 11:09
Perhaps this is a job for `purescript-foreign` then? Could add some more read variants for handling int/int with radix/float/NaN rejection.

**Comment by sharkdp** [comment] 2017-04-16 07:49
In the meantime, [purescript-integers](https://github.com/purescript/purescript-integers) includes a safe version of `readInt`:
``` purs
fromString :: String -> Maybe Int
```
(see https://github.com/purescript/purescript-integers/issues/17)

Also, the latest version of my [purescript-numbers](https://pursuit.purescript.org/packages/purescript-numbers/) library includes the following safe alternative to `readFloat`:
``` purs
fromString :: String -> Maybe Number
```

**Comment by safareli** [comment] 2017-05-01 15:05
btw depending on Maybe could have been avoided using `Alternative`.

**Comment by JordanMartinez** [comment] 2020-10-14 01:04
I think this should be closed as `purescript-numbers` has a `fromString` function that implements this. Otherwise, we'll need to make this repo depend on `maybe`.

**Comment by hdgarrood** [comment] 2020-10-14 01:09
This repo does now depend on `maybe`, since #18 was merged, so we could update these to use Maybe now, and that arguably would make more sense since we are already using Maybe for the encode/decodeURI functions.

**Comment by hdgarrood** [comment] 2020-10-14 01:33
Or, we could deprecate the library (#22) and sidestep the issue entirely.

**Comment by JordanMartinez** [comment] 2020-11-13 23:55
When porting the `Number`-related code from this repo to `purescript-numbers`, the following decisions were made:
- [`readFloat` was dropped in favor of the safer `fromString`](https://github.com/purescript/purescript-numbers/pull/12#discussion_r521610088)
- [`readInt`](https://github.com/purescript/purescript-numbers/pull/12#discussion_r521609397) was dropped entirely. If it needs to be added again, one should submit a PR to `purescript-integers`.

**Closed** 2020-12-17 20:25 UTC
